### ISSUE TITLE
replay stutter

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/grad_replay#26]
@nomisum said:
>to me it looks like the order of the replay fragments is wrongly assembled in some cases, which leads to stuttering especially in the beginning of the recording (little judder)

Stutter can be seen here:
https://www.youtube.com/watch?v=A49nySbgScQ&feature=youtu.be

If you watch closely, you can see the progress bar stutter with it. This means that the actual playback is stuttering, instead of a mixup in the data sequence.

It goes away when I comment this out:
https://github.com/gruppe-adler/grad-replay/blob/master/functions/player/fn_startPlaybackClient.sqf#L89-L91

```
[{
    [grad_replay_playbackPosition] remoteExec ["GRAD_replay_fnc_syncPlaybackPos", [0,-2] select isDedicated, false];
},1,[]] call CBA_fnc_addPerFrameHandler;
```

**Comment by nomisum** [comment]
ah so this is what zade proposed as a fix for the skipping desync (which i dont believe will work for that)

but indeed the sync every second is not necessary. i will do a PR soon.
