### ISSUE TITLE
slow down replay on tense moments

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/grad_replay#4]
possible solution:
add fired EH and accumulate those in a var, if var > 0 mark cluster as slowed (pic stays for 1s instead 0.1). reset var after storing.

**Comment by Fusselwurm** [comment]
how about: slow down replay if someone triggers it? like: people can press `[+]` and `[-]`  to slow down / speed up via a global var that's being broadcast (frame timeout/ time between frames, whatever).

that way, people can decide for themselves which moments were the interesting ones. 

to prevent a single person from dominating everything by keyspamming (++++++++), you could limit this to a majority decision (i.e. everyone can select from 3 speeds, and the speed wanted by most is applied).

**Comment by nomisum** [comment]
i tried something similar back with markers and it was a mess. majority decision would need everyone to participate/cooperate too. maybe its best to make it admin only.

**Comment by nomisum** [comment]
play / pause is implemented
