### ISSUE TITLE
Very Low Framerate after Coop Mission

### ISSUE THREAD

**Issue by Peer202** [gruppe-adler/grad_replay#46]
I just used this script as a ingame replay for a Coop Event with 30 Players. During testing the Issue never came up, but in the final event most players experienced very low framerate and a long assembly time. The Mission had a lot of objects in it( about 1700). Its seems that the objects were marked in the replay, Is this intendet? Could this have affected performance? Is there a way to disable the tracking of Objects while still tracking vehicles? I couldnt find anything in the documentation about this. 

This is the Config i used:
```

class GRAD_Replay {
    precision = 3;
    trackedSides[] = {"west", "east","independent"};
    stepsPerTick = 1; 
    trackedVehicles = 1; 
    trackedAI = 1; 
    sendingChunkSize = 10; 
    trackShots = 1; 
    upload = 0; 
};
```

**Comment by nomisum** [comment]
Set "trackedVehicles" to 0

Note this slso disables tracking of empty (!) AI vehicles but this might not be needed anyway.

I might also tweak the algorithm a bit, its currently not very smart detecting interesting object

Edit: And yes tracking multitudes of entities is taxing on the server, even tracking 100 units for 3 hours requires dropping precision.

**Comment by Peer202** [comment]
Ok, does switching off this setting still track the players vehicle if they are dismounted?  Is there an option to track only "interesting " AI movements, so for example every AI withing one Kilometer from the nearest players out side of moving vehicles or similar. That could reduce Load as well, if only the AI is tracked that guards the current objective or is in pursuit of the playsers and the rest is not. 

I will try to reduce the tracking precision and set trackedVehicles to 0.
Thank you

**Comment by nomisum** [comment]
> Ok, does switching off this setting still track the players vehicle if they are dismounted?

no, it does not know if a vehicle was in players posession before

> Is there an option to track only "interesting " AI movements, so for example every AI withing one Kilometer from the nearest players out side of moving vehicles or similar. That could reduce Load as well, if only the AI is tracked that guards the current objective or is in pursuit of the players and the rest is not.

Currently not implemented. I will think about it, should not be too much effort.
