### ISSUE TITLE
Progressbar Hintergrund verschwindet, wenn man draufklickt

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/grad_replay#9]
![20171030211234_1](https://user-images.githubusercontent.com/16549968/32193339-3eb8ca58-bdb7-11e7-8b89-97048398d212.jpg)

![20171030211237_1](https://user-images.githubusercontent.com/16549968/32193340-3ed332d0-bdb7-11e7-9f81-9d7fe0e8d61b.jpg)

**Comment by nomisum** [comment]
hab schon mal länger rumprobiert, aber kein setting gefunden, was da greift.
